---

require:
  - rubocop-minitest
  - rubocop-rake

inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable

Lint/Void:
  Exclude:
    - lib/toxiproxy.rb

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false
